version: '3'
services:
  db_val_social:
    image: postgres
    container_name: val_social_database
    restart: always
    ports:
      - "5452:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
